name: Test Student Android Projects

on:
  pull_request:
    paths:
      - '**/*'  # Trigger for any file change

jobs:
  test-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Find Android projects
      id: find-projects
      run: |
        find . -name 'build.gradle' -exec dirname {} \; > android_projects.txt

    - name: Run Gradle tests for all projects
      run: |
        while read project; do
          echo "Testing project: $project"
          cd $project
          ./gradlew test || ./gradlew build
          cd -
        done < android_projects.txt
